port:  5000
markdown: kramdown
name: "Charts - Institute for Housing Studies - DePaul University"
url: https://charts.housingstudies.org
encoding: utf-8
timezone: America/Chicago
description: "Charts for HousingStudies.org"
author: "Institute for Housing Studies - DePaul University"
plugins:
  - jekyll-redirect-from